# Device Configuration Templates and Parameters
# YAML format for network device configurations

device_configs:
  global_settings:
    domain_name: "company.local"
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
    ntp_servers:
      - "pool.ntp.org"
      - "time.google.com"
    timezone: "EST -5 0"
    
  routing:
    ospf:
      process_id: 1
      router_id: "1.1.1.1"
      networks:
        - network: "192.168.1.0"
          wildcard: "0.0.0.255"
          area: 0
        - network: "10.0.0.0"
          wildcard: "0.255.255.255" 
          area: 0
          
    bgp:
      asn: 65001
      router_id: "2.2.2.2"
      neighbors:
        - ip: "192.168.1.2"
          remote_as: 65002
        - ip: "192.168.1.3"
          remote_as: 65003

  vlans:
    - id: 10
      name: "Management"
      description: "Network Management VLAN"
    - id: 20
      name: "Users" 
      description: "User Access VLAN"
    - id: 30
      name: "Servers"
      description: "Server VLAN"
    - id: 40
      name: "Guest"
      description: "Guest Access VLAN"
      
  interfaces:
    management:
      - name: "GigabitEthernet0/0"
        description: "WAN Interface"
        ip: "203.0.113.10"
        mask: "255.255.255.252"
      - name: "GigabitEthernet0/1" 
        description: "LAN Interface"
        ip: "192.168.1.1"
        mask: "255.255.255.0"
        
    loopbacks:
      - number: 0
        ip: "1.1.1.1"
        mask: "255.255.255.255"
        description: "Primary Loopback"
      - number: 1
        ip: "10.10.10.10" 
        mask: "255.255.255.255"
        description: "Secondary Loopback"

  security:
    enable_password: "cisco123"
    username_password:
      - username: "admin"
        password: "admin123"
        privilege: 15
      - username: "operator"
        password: "oper123"
        privilege: 1
        
    access_lists:
      - name: "MGMT_ACCESS"
        type: "extended"
        rules:
          - "permit tcp 192.168.100.0 0.0.0.255 any eq 22"
          - "permit tcp 192.168.100.0 0.0.0.255 any eq 443"
          - "deny ip any any"

  snmp:
    version: "2c"
    community:
      - name: "public"
        permission: "ro"
      - name: "private"  
        permission: "rw"
    location: "Network Closet A"
    contact: "network-admin@company.com"